version:
  '3.8'

services:
  postgres:
    image: postgres:12-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: go_ecommerce_shop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/tmp/localstack/data
      - LOCALSTACK_AUTH_TOKEN=ls-WelE4748-PisE-PIki-7780-toxiJeGU775f
    ports:
      - "4566:4566"
    volumes:
      - localstack_data:/var/lib/localstack
      - ./init/aws/init-localstack.sh:/etc/localstack/init/ready.d/init.sh
volumes:
  postgres_data:
  localstack_data:
